/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace ptz_camera
{
    public sealed class ptz_control_request_t : LCM.LCM.LCMEncodable
    {
        public int mode;
        public String ip_address;
        public byte pan_value;
        public byte tilt_value;
        public byte zoom_value;
 
        public ptz_control_request_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x6dd57de349000b54L;
 
        public const int ABSOLUTE = 1;
        public const int RELATIVE = 2;

        static ptz_control_request_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("ptz_camera.ptz_control_request_t"))
                return 0L;
 
            classes.Add("ptz_camera.ptz_control_request_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.mode); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.ip_address); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.pan_value); 
 
            outs.Write(this.tilt_value); 
 
            outs.Write(this.zoom_value); 
 
        }
 
        public ptz_control_request_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public ptz_control_request_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static ptz_camera.ptz_control_request_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            ptz_camera.ptz_control_request_t o = new ptz_camera.ptz_control_request_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.mode = ins.ReadInt32();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.ip_address = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.pan_value = ins.ReadByte();
 
            this.tilt_value = ins.ReadByte();
 
            this.zoom_value = ins.ReadByte();
 
        }
 
        public ptz_camera.ptz_control_request_t Copy()
        {
            ptz_camera.ptz_control_request_t outobj = new ptz_camera.ptz_control_request_t();
            outobj.mode = this.mode;
 
            outobj.ip_address = this.ip_address;
 
            outobj.pan_value = this.pan_value;
 
            outobj.tilt_value = this.tilt_value;
 
            outobj.zoom_value = this.zoom_value;
 
            return outobj;
        }
    }
}

