/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace ptz_camera
{
    public sealed class stop_program_request_t : LCM.LCM.LCMEncodable
    {
 
        public stop_program_request_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0000000012345678L;
 
        static stop_program_request_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("ptz_camera.stop_program_request_t"))
                return 0L;
 
            classes.Add("ptz_camera.stop_program_request_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
        }
 
        public stop_program_request_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public stop_program_request_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static ptz_camera.stop_program_request_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            ptz_camera.stop_program_request_t o = new ptz_camera.stop_program_request_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
        }
 
        public ptz_camera.stop_program_request_t Copy()
        {
            ptz_camera.stop_program_request_t outobj = new ptz_camera.stop_program_request_t();
            return outobj;
        }
    }
}

